baseURL = 'https://stefanopulze.com/'
languageCode = 'it-IT'
title = 'Stefano Pulze'
theme = 'me-22'
defaultContentLanguage = 'it'
googleAnalytics = 'G-GZEH8CJ8G0'

[markup]
    [markup.highlight]
        style = 'monokai'

enableRobotsTXT= true
disableKinds = ['taxonomy','term','categories','rss','sitemap']