baseURL: "https://stefanopulze.com/"
languageCode: "it-IT"
defaultContentLanguage: 'it'
title: 'Stefano Pulze'
theme: 'me-22'
googleAnalytics: 'G-GZEH8CJ8G0'

enableRobotsTXT: true
disableKinds:
  - taxonomy
  - term
  - categories
  - rss
  - sitemap